env_name: "cube-single-play-v0"
max_path_length: 1001

planner_horizon: 81
invdyn_horizon: 15 # for invdyn diffusion training
planner_temperature: 1.0
w_ldg: 0

jump_steps: 5
low_horizon: 10
goal_tol: 2.0
replan_error_threshold: 3.5
replan_every: 100